import { useRef, useState } from 'react';
import type { StudioProject, LootItem } from '../core/types';
import { MAX_ITEMS, MAX_URI_LENGTH, MAX_ADDRESS_LENGTH } from '../core/project';
import { parseItemsImport, itemSetErrors } from '../core/item-import';
import type { ItemImport } from '../core/item-import';
import { downloadText } from '../core/export';
import { MetadataPreview } from '../components/MetadataPreview';
import { Choices, Field, FieldHelp, NumberField, TokenIdField } from '../components/Fields';
import { Modal } from '../components/Modal';
const CSV_TEMPLATE = 'name,metadataUri,weight,tokenId\r\nIron shard,,70,0\r\nMoonstone,,25,1\r\n"Ancient, relic",,5,2\r\n';
export type ConfigPage = 'overview' | 'mechanic' | 'payment' | 'modules';
export function ConfigEditor({ project: p, page, update, navigate, report }: { project: StudioProject; page: ConfigPage; update: (edit: (p: StudioProject) => void) => void; navigate: (page: ConfigPage | 'files' | 'agent') => void; report: (key: string, invalid: boolean) => void }) {
  const [removed, setRemoved] = useState<{ item: LootItem; index: number }>();
  const [replaced, setReplaced] = useState<LootItem[]>();
  const [itemImport, setItemImport] = useState<ItemImport>();
  const [importOpen, setImportOpen] = useState(false);
  const importInput = useRef<HTMLInputElement>(null);
  const appendErrors = itemImport ? itemSetErrors([...p.loot.items, ...itemImport.items]) : [];
  const total = p.loot.items.reduce((sum, item) => sum + item.weight, 0);
  const numeric = (key: string) => ({ report, fieldKey: key });
  const revealLabels = { shuffle: 'Shuffle', offset: 'Index offset', 'token-hash': 'Per-token hash' };
  const revealDescriptions = {
    shuffle: 'An independent permutation of each frozen batch, with up to 256 tokens per SDK request. This is a batch-local shuffle, not one global permutation of the collection.',
    offset: 'A cyclic rotation of the frozen, currently minted batch. Each index appears once, but only rotations are possible. This mode has no 256-token batch cap; it is not a full shuffle.',
    'token-hash': 'A VRF-derived seed getter for each token in the frozen batch. Your coding agent must define how seeds become metadata or traits. This mode does not promise unique metadata assignments.',
  };
  const revealMetadataHelp = p.reveal.mode === 'token-hash'
    ? p.integration === 'new'
      ? 'After a batch is finalized, tokenURI uses this exact prefix plus tokenId and .json. Include a trailing slash when needed. The seed getter does not generate metadata content or traits; your coding agent must implement that mapping.'
      : 'Metadata hosting reference for your host integration. The adapter exposes derived token seeds; your coding agent must define the existing collection’s metadata URLs and trait mapping.'
    : 'Final HTTPS, IPFS or Arweave prefix for token metadata. The new collection uses this exact prefix plus the assigned metadata index and .json. Include a trailing slash when needed. Existing collections must implement their own host integration.';
  async function importItems(file?: File) {
    if (!file) return;
    try {
      if (file.size > 512 * 1024) throw new Error('Item imports must be 512 KB or smaller.');
      setItemImport(parseItemsImport(await file.text(), file.name.toLowerCase().endsWith('.csv') ? 'csv' : 'json'));
    } catch (error) { setItemImport({ items: [], errors: [error instanceof Error ? error.message : 'Could not read import.'] }); }
    setImportOpen(true);
    if (importInput.current) importInput.current.value = '';
  }
  function applyImport(replace: boolean) {
    if (!itemImport || itemImport.errors.length || (!replace && appendErrors.length)) return;
    if (replace) setReplaced(structuredClone(p.loot.items));
    if (replace) for (const item of p.loot.items) { report(`weight-${item.id}`, false); report(`token-${item.id}`, false); }
    update(d => { d.loot.items = replace ? itemImport.items : [...d.loot.items, ...itemImport.items]; });
    setRemoved(undefined); setImportOpen(false);
  }
  return <div className="config-layout"><div className="config-main">
    {page === 'overview' && <>
      <h2>Project overview</h2><p className="lead">Configure your project settings and generation target.</p>
      <div className="fields three"><Field path="name" help="Name used in your local project list and exported project specification. This is separate from the NFT collection name." label="Project name"><input value={p.name} maxLength={80} onChange={e => update(d => { d.name = e.target.value; })} /></Field>
        <Field path="mechanic" help="Lootbox selects one reward by integer weights. NFT reveal uses a selected VRF-based reveal mode for batches of minted ERC-721 tokens. Changing this also selects the matching asset standard." label="Mechanic"><select value={p.mechanic} onChange={e => update(d => { d.mechanic = e.target.value as StudioProject['mechanic']; d.collection.standard = d.mechanic === 'reveal' ? 'erc721' : 'erc1155'; })}><option value="lootbox">Lootbox</option><option value="reveal">NFT reveal</option></select></Field>
        <Field path="collection.standard" help="Use ERC-1155 for the loot template and ERC-721 for the reveal template. Unsupported combinations produce configuration errors." label="Asset standard"><select value={p.collection.standard} onChange={e => update(d => { d.collection.standard = e.target.value as StudioProject['collection']['standard']; })}><option value="erc1155">ERC-1155</option><option value="erc721">ERC-721</option></select></Field></div>
      <section className="ruled"><Choices path="integration" help="New project exports a collection and consumer. Existing project exports an adapter and instructions; it does not edit your repository." label="Generation target" value={p.integration} onChange={v => update(d => { d.integration = v; })} options={[{ value: 'new', label: 'New project', description: 'Start with a consumer scaffold, configuration and agent instructions.' }, { value: 'existing', label: 'Existing project', description: 'Export boilerplate for manual integration. Your repository is not edited automatically.' }]} /></section>
      <section className="ruled"><h3>Target network</h3><Field path="network" help="Select the chain your integration will use. This is a static reference, not a wallet connection or live deployment check. Verify the manifest before deployment." label="Deployment reference" hint="Confirm the manifest and live configuration before integration."><select value={p.network} onChange={e => update(d => { d.network = e.target.value as StudioProject['network']; })}><option value="arc-testnet">Arc Testnet · static reference</option><option value="arc-mainnet">Arc Mainnet · static reference</option></select></Field></section>
      <div className="actions"><button className="primary" onClick={() => navigate('mechanic')}>{p.mechanic === 'lootbox' ? 'Configure items' : 'Configure reveal'} →</button><button onClick={() => navigate('files')}>View files</button></div>
    </>}
    {page === 'mechanic' && <>
      <h2>{p.mechanic === 'lootbox' ? 'Items & weights' : 'Reveal settings'}</h2><p className="lead">{p.mechanic === 'lootbox' ? 'One independent weighted draw per opening.' : 'Reveal minted tokens in batches as your collection grows.'}</p>
      <div className="fields"><Field path="collection.name" help="Display name for your NFT collection, included in the generated collection and configuration. Up to 80 characters." label="Collection name"><input value={p.collection.name} maxLength={80} onChange={e => update(d => { d.collection.name = e.target.value; })} /></Field><Field path="collection.symbol" help="Short collection identifier. Use 1–16 letters, numbers, underscores or hyphens." label="Symbol"><input value={p.collection.symbol} maxLength={16} onChange={e => update(d => { d.collection.symbol = e.target.value; })} /></Field></div>
      <section className="supply-settings"><Choices path="collection.supply" label="Collection supply" help="Unlimited adds no total mint cap. Limited uses the maximum you enter, counting premints too. Reveal batches are independent of this supply policy." value={p.collection.maxSupply === null ? 'unlimited' : 'limited'} onChange={value => { report('max-supply', false); update(d => { d.collection.maxSupply = value === 'unlimited' ? null : 0; }); }} options={[{ value: 'unlimited', label: 'Unlimited', description: 'No total mint cap.' }, { value: 'limited', label: 'Limited', description: 'Set your own maximum supply.' }]} />
        {p.collection.maxSupply !== null && <NumberField key="supply-cap" path="collection.maxSupply" label="Maximum supply" help="The collection-wide cap you choose. Preminted units and, for lootboxes, outstanding reward reservations count toward it." value={p.collection.maxSupply} min={1} emptyWhenZero placeholder="Enter maximum supply" onChange={n => update(d => { d.collection.maxSupply = n; })} {...numeric('max-supply')} />}
      </section>
      {p.mechanic === 'lootbox' ? <>
        <div className="table-scroll"><table className="items-table metadata-items"><thead><tr><th><span className="sr-only">Preview</span></th><th>Item</th><th>Metadata URI <FieldHelp label="Item metadata URI">HTTPS, IPFS or Arweave JSON reference. Up to 512 characters. Metadata previews do not change item names unless you choose Use metadata name.</FieldHelp></th><th>Token ID <FieldHelp label="Item token ID">Unique decimal uint256 ID. Leave blank to use the current row index. ERC-1155 {'{id}'} placeholders resolve to 64 lowercase hexadecimal characters.</FieldHelp></th><th>Weight <FieldHelp label="Item weight">Whole number from 0 to 1,000,000. A weight of zero excludes an item. At least one weight must be positive.</FieldHelp></th><th>Chance <FieldHelp label="Derived chance">Item weight divided by total weight, recalculated automatically. Each opening is an independent draw; rarity counts are not guaranteed.</FieldHelp></th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{p.loot.items.map((item, i) => {
          const tokenId = item.tokenId ?? String(i);
          const duplicate = p.loot.items.some((other, j) => j !== i && (other.tokenId ?? String(j)) === tokenId);
          return <tr key={item.id}><td><MetadataPreview uri={item.metadataUri} tokenId={tokenId} itemName={item.name} onUseName={name => update(d => { d.loot.items[i].name = name; })} /></td>
            <td><input data-field-path={`loot.items.${i}.name`} aria-label={`Item ${i + 1} name`} value={item.name} maxLength={80} onChange={e => update(d => { d.loot.items[i].name = e.target.value; })} /></td>
            <td><input data-field-path={`loot.items.${i}.metadataUri`} aria-label={`${item.name || `Item ${i + 1}`} metadata URI`} value={item.metadataUri} maxLength={MAX_URI_LENGTH} onChange={e => update(d => { d.loot.items[i].metadataUri = e.target.value; })} /></td>
            <td><TokenIdField path={`loot.items.${i}.tokenId`} label={`${item.name || `Item ${i + 1}`} token ID`} value={item.tokenId} fallback={String(i)} duplicate={duplicate} report={report} fieldKey={`token-${item.id}`} onChange={value => update(d => { if (value === undefined) delete d.loot.items[i].tokenId; else d.loot.items[i].tokenId = value; })} /></td>
            <td><NumberField path={`loot.items.${i}.weight`} label={`Weight for ${item.name || `item ${i + 1}`}`} value={item.weight} max={1_000_000} onChange={n => update(d => { d.loot.items[i].weight = n; })} {...numeric(`weight-${item.id}`)} /></td>
            <td className="mono">{total > 0 ? `${(item.weight / total * 100).toFixed(1)}%` : '—'}</td>
            <td><button className="icon-button" aria-label={`Remove ${item.name || `item ${i + 1}`}`} onClick={() => { setRemoved({ item, index: i }); report(`weight-${item.id}`, false); report(`token-${item.id}`, false); update(d => { d.loot.items.splice(i, 1); }); }}>×</button></td></tr>;
        })}</tbody></table></div>
        {p.loot.items.length === 0 && <p className="notice">Add an item to define your loot table.</p>}
        <p className="token-id-hint">Blank token IDs use the row index. ERC-1155 {'{id}'} is replaced with 64 lowercase hexadecimal characters. Chance is calculated from weights.</p>{p.integration === 'new' && <p className="token-id-hint">Item URIs are committed when files are generated. Small tables are stored at deployment; larger tables register their remaining items afterwards with the exported proofs.</p>}
        <div className="actions item-actions"><button data-field-path="loot.items" disabled={p.loot.items.length >= MAX_ITEMS} onClick={() => update(d => { d.loot.items.push({ id: crypto.randomUUID(), name: '', metadataUri: '', weight: 1 }); })}>+ Add item</button>{removed && <button disabled={p.loot.items.length >= MAX_ITEMS} onClick={() => { update(d => { d.loot.items.splice(Math.min(removed.index, d.loot.items.length), 0, removed.item); }); setRemoved(undefined); }}>Undo removal</button>}{replaced && <button onClick={() => { for (const item of p.loot.items) { report(`weight-${item.id}`, false); report(`token-${item.id}`, false); } update(d => { d.loot.items = replaced; }); setReplaced(undefined); }}>Undo replacement</button>}</div>
        <section className="import-guide" aria-label="Item import format"><div className="import-heading"><div><h3>Import items</h3><p>Review your rows before adding them to this table.</p></div><div className="import-actions"><button type="button" onClick={() => downloadText('d20dao-items-template.csv', CSV_TEMPLATE, 'text/csv;charset=utf-8')} aria-label="Download CSV template">CSV template ↓</button><button type="button" className="primary" onClick={() => importInput.current?.click()}>Import JSON / CSV</button></div></div><p className="import-format-line">CSV headers: <code>name,metadataUri,weight,tokenId</code><span> · tokenId is optional</span></p><details><summary>Format, example and limits</summary><pre tabIndex={0} aria-label="CSV import example">{CSV_TEMPLATE}</pre><ul><li>Import 1–256 items, at most 512 KB. Name: 1–80 characters. Metadata URI: at most 512 characters; blank is allowed.</li><li>Weights are integers from 0 to 1,000,000, with a positive total. Use lowercase https://, ipfs:// or ar:// metadata references.</li><li>Token IDs are optional decimal uint256 values, without leading zeros. Blank IDs use final row indexes and must remain unique. Keep long IDs as text in your spreadsheet.</li><li>Quote values containing commas, quotes or newlines; escape a quote by doubling it. The template includes a quoted comma example.</li><li>JSON accepts an array, or an object with an items array. Each item contains name, metadataUri, weight and an optional tokenId string.</li></ul></details></section>
        <input ref={importInput} type="file" accept=".json,.csv,application/json,text/csv" className="sr-only" aria-label="Import loot items" onChange={e => importItems(e.target.files?.[0])} />
        <Modal open={importOpen} onClose={() => setImportOpen(false)} title="Review item import" className="item-import-modal" footer={<><button type="button" data-modal-initial-focus onClick={() => setImportOpen(false)}>Cancel import</button><button type="button" disabled={!itemImport || itemImport.errors.length > 0 || appendErrors.length > 0} onClick={() => applyImport(false)}>Append items</button><button type="button" className="primary" disabled={!itemImport || itemImport.errors.length > 0} onClick={() => applyImport(true)}>Replace table</button></>}>
          {itemImport && <div className="item-import"><p>{itemImport.items.length} parsed items. Append them to the current table, or replace its {p.loot.items.length} rows.</p>{itemImport.errors.length > 0 && <ul className="import-errors" role="alert">{itemImport.errors.map((error, i) => <li key={i}>{error}</li>)}</ul>}{itemImport.items.length > 0 && <div className="table-scroll" tabIndex={0} aria-label="Imported items"><table><thead><tr><th>Name</th><th>Weight</th><th>Token ID</th><th>Metadata URI</th></tr></thead><tbody>{itemImport.items.map((item, i) => <tr key={item.id}><td>{item.name}</td><td>{item.weight}</td><td>{item.tokenId ?? `Row index (${i})`}</td><td>{item.metadataUri || 'Not provided'}</td></tr>)}</tbody></table></div>}{appendErrors.length > 0 && <p className="muted">Append unavailable: {appendErrors.join(' ')}</p>}<p className="muted">Replacing the table keeps one undo snapshot. Preview images are not imported.</p></div>}
        </Modal>
      </> : <>
        <Field path="reveal.mode" label="Reveal mode" help="Choose the algorithm for each frozen batch. Shuffle permutes up to 256 entries per SDK request. Index offset rotates the batch without that limit. Per-token hash exposes derived seeds for your agent to map into metadata or traits. Supply policy is independent of this choice.">
          <select value={p.reveal.mode} onChange={event => update(d => { d.reveal.mode = event.target.value as StudioProject['reveal']['mode']; })}>
            <option value="shuffle">Shuffle</option><option value="offset">Index offset</option><option value="token-hash">Per-token hash</option>
          </select>
        </Field>
        <p className="reveal-mode-description">{revealDescriptions[p.reveal.mode]}</p>
        <Field path="collection.metadataBaseUri" help={revealMetadataHelp} label="Metadata base URI"><input maxLength={MAX_URI_LENGTH} value={p.collection.metadataBaseUri} onChange={e => update(d => { d.collection.metadataBaseUri = e.target.value; })} placeholder="ipfs://collection/" /></Field>
        <Field path="reveal.unrevealedUri" help={p.integration === 'new' ? 'Complete metadata JSON reference returned by tokenURI for every minted token that is not revealed yet, such as a mystery-box image. Leave blank to return an empty tokenURI. It is fixed at deployment.' : 'Placeholder metadata your host collection should return for unrevealed tokens. Recorded as an integration requirement.'} label="Unrevealed placeholder URI"><input maxLength={MAX_URI_LENGTH} value={p.reveal.unrevealedUri} onChange={e => update(d => { d.reveal.unrevealedUri = e.target.value; })} placeholder="ipfs://collection/unrevealed.json" /></Field>
        <section className="ruled"><h3>{p.integration === 'new' ? 'Reveal as you mint' : 'Freeze your host batch'} <FieldHelp label="Reveal batches">{revealDescriptions[p.reveal.mode]} An expired attempt retries the same frozen batch. An accepted result is retained for delivery retries; it is never replaced by a fresh draw.</FieldHelp></h3><p className="muted">{p.integration === 'new'
          ? 'Minting can continue while a frozen batch is being revealed. Apply its accepted result once; tokens minted later enter a later batch. Premint participation follows your module settings.'
          : 'The exported adapter does not implement your existing NFT collection. Your host integration must freeze the participating token list or range, bind it to the request, and apply the accepted result without changing that list.'}</p>{p.reveal.mode === 'token-hash' && <p className="muted">The seed getter is a starting point. Your agent must implement and test metadata or trait resolution for your application.</p>}</section>
      </>}
      <section className="ruled"><h3>Optional modules</h3><p className="muted">{p.integration === 'new' ? 'Premint and royalties are included in the new collection template. Review configuration and contract behavior before deployment.' : 'Premint and royalty choices become requirements for your existing collection integration.'}</p><button onClick={() => navigate('modules')}>Configure modules →</button></section>
      <div className="actions"><button className="primary" onClick={() => navigate('files')}>View generated files →</button></div>
    </>}
    {page === 'payment' && <>
      <h2>Payment & recovery</h2><p className="lead">Configure application payments, RNG fee payer and recovery responsibility.</p>
      <p className="notice">Application sale pricing, fee sponsorship and custom refund routing are exported as integration requirements. The reference consumer charges only the RNG fee.{p.mechanic === 'lootbox' && ' As generated, anyone can open by paying that fee; your agent enforces entitlement or a price in _authorizeOpen.'}</p><h3>Application payment</h3><Field path="payment.price" help="Application sale price, separate from the coordinator RNG fee. This value is exported as an integration requirement; the reference consumer does not collect this sale payment." label="Price per opening or mint (USDC)" hint="Application payments are accounted for separately from the RNG fee."><input inputMode="decimal" value={p.payment.price} onChange={e => update(d => { d.payment.price = e.target.value; })} /></Field>
      <Field path="payment.applicationRefund" help="Defines how your application handles its own sale payment when no proof is accepted. A protocol RNG refund does not automatically refund the application price." label="Application payment on expiry"><select value={p.payment.applicationRefund} onChange={e => update(d => { d.payment.applicationRefund = e.target.value as StudioProject['payment']['applicationRefund']; })}><option value="refund-on-expiry">Refund when no proof is accepted</option><option value="developer-defined">Developer-defined recovery</option></select></Field>
      <section className="ruled"><h3>Randomness fee</h3><Choices path="payment.rngPayer" help="Who should fund randomness in the finished application. Developer sponsorship is an integration requirement; the reference consumer accepts the RNG fee from its caller." label="RNG fee payer" value={p.payment.rngPayer} options={[{ value: 'user', label: 'User' }, { value: 'developer', label: 'Developer' }]} onChange={v => update(d => { d.payment.rngPayer = v; })} />
      <Field path="payment.refundRecipient" help="Recipient policy for protocol refunds. The address is fixed when a request is submitted. Custom routing requires integration work; the reference consumer fixes the recipient to its caller." label="Fixed refund recipient policy" hint="Snapshot the recipient address when requesting randomness."><select value={p.payment.refundRecipient} onChange={e => update(d => { d.payment.refundRecipient = e.target.value as StudioProject['payment']['refundRecipient']; })}><option value="payer">Original payer</option><option value="developer">Developer</option><option value="custom">Custom recipient</option></select></Field>
      {p.payment.refundRecipient !== 'payer' && <Field path="payment.refundAddress" help="Required public address for the chosen developer or custom refund route. Never enter a private key. The routing must be implemented in the integration." label="Public refund recipient address"><input maxLength={MAX_ADDRESS_LENGTH} value={p.payment.refundAddress} placeholder="0x…" onChange={e => update(d => { d.payment.refundAddress = e.target.value; })} /></Field>}</section>
      <section className="ruled"><Choices path="payment.recovery" help="Who your application asks to submit recovery transactions. This does not restrict the coordinator: protocol refunds are permissionless and pay the fixed recipient." label="Recovery handled by" value={p.payment.recovery} options={[{ value: 'user', label: 'User' }, { value: 'developer', label: 'Developer' }, { value: 'both', label: 'Both' }]} onChange={v => update(d => { d.payment.recovery = v; })} /><p className="muted">Defines who your application asks to submit recovery transactions.</p><p className="notice">Protocol refunds are permissionless and pay the fixed recipient.</p></section>
    </>}
    {page === 'modules' && <>
      <h2>Optional modules</h2><p className="lead">Record the collection features for your implementation brief.</p>
      <details className="module" open><summary>Premint</summary><div className="check-with-help"><label className="check"><input data-field-path="modules.premint.enabled" type="checkbox" checked={p.modules.premint.enabled} onChange={e => { if (!e.target.checked) report('premint', false); update(d => { d.modules.premint.enabled = e.target.checked; }); }} /> Include premint requirements</label><FieldHelp label="Premint module">Include an initial allocation in the new collection template, or record the requirement for an existing collection.</FieldHelp></div>{p.modules.premint.enabled && <><div className="fields"><NumberField path="modules.premint.quantity" help="Initial allocation, counted within your supply cap when one is set. ERC-1155 premint uses the first item ID. ERC-721 premint is distributed with mintPremint before regular minting, and occupies the initial token-ID prefix." label="Premint quantity" value={p.modules.premint.quantity} max={p.collection.maxSupply ?? undefined} onChange={n => update(d => { d.modules.premint.quantity = n; })} {...numeric('premint')} /><Field path="modules.premint.recipient" help="Complete, nonzero public address receiving the preminted units. This is a recipient address, never a signing key." label="Allocation recipient"><input placeholder="Public recipient address" maxLength={MAX_ADDRESS_LENGTH} value={p.modules.premint.recipient} onChange={e => update(d => { d.modules.premint.recipient = e.target.value; })} /></Field></div>{p.mechanic === 'reveal' && <div className="check-with-help"><label className="check"><input data-field-path="modules.premint.includeInReveal" type="checkbox" checked={p.modules.premint.includeInReveal} onChange={e => update(d => { d.modules.premint.includeInReveal = e.target.checked; })} />Include premints in reveal</label><FieldHelp label="Premint reveal participation">Included premints participate in reveal batches. Excluded premints retain their original metadata; only later, non-preminted tokens enter the reveal queue.</FieldHelp></div>}<p className="muted">{p.modules.premint.quantity} tokens allocated before regular minting{p.collection.maxSupply === null ? '.' : `, within the ${p.collection.maxSupply} supply cap.`}</p>{p.integration === 'new' && p.mechanic === 'lootbox' && <p className="muted">Premint allocates the first configured item token ID. Maximum supply counts all NFT units, including premints and reserved openings.</p>}</>}</details>
      <details className="module" open><summary>Royalties</summary><div className="check-with-help"><label className="check"><input data-field-path="modules.royalty.enabled" type="checkbox" checked={p.modules.royalty.enabled} onChange={e => { if (!e.target.checked) report('royalty', false); update(d => { d.modules.royalty.enabled = e.target.checked; }); }} /> Include royalty requirements</label><FieldHelp label="Royalty module">Include ERC-2981 royalty signaling for a new collection, or record integration requirements for an existing collection.</FieldHelp></div>{p.modules.royalty.enabled && <div className="fields"><NumberField path="modules.royalty.bps" help="100 basis points = 1%; 500 = 5%. ERC-2981 reports this royalty rate but does not force every marketplace to pay it." label="Royalty rate (basis points)" value={p.modules.royalty.bps} max={10000} onChange={n => update(d => { d.modules.royalty.bps = n; })} {...numeric('royalty')} /><Field path="modules.royalty.recipient" help="Complete, nonzero public address returned by ERC-2981 royaltyInfo. Marketplace royalty payments, if supported, go to this receiver." label="Royalty receiver"><input placeholder="0x…" maxLength={MAX_ADDRESS_LENGTH} value={p.modules.royalty.recipient} onChange={e => update(d => { d.modules.royalty.recipient = e.target.value; })} /></Field></div>}<p className="muted">{p.modules.royalty.bps / 100}% · ERC-2981 signals royalties; marketplaces decide enforcement.</p></details>
      <p className="notice">{p.integration === 'new' ? 'The new collection template includes selected premint and royalty behavior. Sale payments, fee sponsorship and custom refund policies remain integration work.' : 'Module settings update the configuration and agent brief for your existing collection. Implement and test the required hooks in your application.'}</p><button className="primary" onClick={() => navigate('files')}>View generated files →</button>
    </>}
  </div><aside className="summary-rail">
    {page === 'payment' ? <><h3>Recovery rules</h3><p>60 seconds is the proof-acceptance deadline.</p><hr /><p>Expired without accepted proof: request the protocol refund.</p><hr /><p>Accepted proof, failed callback: retry the same word. No RNG fee refund.</p><hr /><p className="muted">Application delivery is defined by your integration.</p></> : page === 'modules' ? <><h3>Included in export</h3><p>Project configuration</p><p>AGENTS.md</p><p>Agent prompt</p><hr /><p className="muted">Generated files and instructions reflect the same choices.</p></> : p.mechanic === 'lootbox' ? <><h3>{page === 'mechanic' ? 'Probability' : 'Configuration'}</h3>{p.loot.items.map(item => <div className="probability" key={item.id}><div><span>{item.name || 'Unnamed item'}</span><span>{total > 0 ? `${(item.weight / total * 100).toFixed(1)}%` : '—'}</span></div><div className="bar"><span style={{ width: `${total > 0 ? item.weight / total * 100 : 0}%` }} /></div></div>)}<hr /><p>Total weight <span className="right">{total}</span></p><p className="muted">Independent draws do not guarantee stock or rarity counts.</p></> : <><h3>Reveal plan</h3><p>{p.collection.maxSupply === null ? 'Unlimited collection supply' : 'Supply cap: ' + p.collection.maxSupply}</p><p>{revealLabels[p.reveal.mode]}</p><p>{p.reveal.mode === 'shuffle' ? 'Up to 256 tokens per batch' : 'No 256-token batch cap'}</p><hr /><p className="muted">{p.reveal.mode === 'shuffle' ? 'Each batch has its own permutation.' : p.reveal.mode === 'offset' ? 'One cyclic rotation per frozen batch.' : 'Per-token seeds; customize metadata and traits.'}</p><p className="muted">{p.integration === 'new' ? 'Reveal minted batches independently of the supply cap.' : 'Your host must freeze the participating token list.'}</p></>}
  </aside></div>;
}
