import { useRef, useState } from 'react';
import type { StudioProject, LootItem } from '../core/types';
import { MAX_ITEMS, MAX_URI_LENGTH, MAX_ADDRESS_LENGTH } from '../core/project';
import { parseItemsImport, itemSetErrors } from '../core/item-import';
import type { ItemImport } from '../core/item-import';
import { MetadataPreview } from '../components/MetadataPreview';
import { Choices, Field, NumberField, TokenIdField } from '../components/Fields';
export type ConfigPage = 'overview' | 'mechanic' | 'payment' | 'modules';
export function ConfigEditor({ project: p, page, update, navigate, report }: { project: StudioProject; page: ConfigPage; update: (edit: (p: StudioProject) => void) => void; navigate: (page: ConfigPage | 'files' | 'agent') => void; report: (key: string, invalid: boolean) => void }) {
  const [removed, setRemoved] = useState<{ item: LootItem; index: number }>();
  const [replaced, setReplaced] = useState<LootItem[]>();
  const [itemImport, setItemImport] = useState<ItemImport>();
  const importInput = useRef<HTMLInputElement>(null);
  const appendErrors = itemImport ? itemSetErrors([...p.loot.items, ...itemImport.items]) : [];
  const total = p.loot.items.reduce((sum, item) => sum + item.weight, 0);
  const numeric = (key: string) => ({ report, fieldKey: key });
  async function importItems(file?: File) {
    if (!file) return;
    try {
      if (file.size > 512 * 1024) throw new Error('Item imports must be 512 KB or smaller.');
      setItemImport(parseItemsImport(await file.text(), file.name.toLowerCase().endsWith('.csv') ? 'csv' : 'json'));
    } catch (error) { setItemImport({ items: [], errors: [error instanceof Error ? error.message : 'Could not read import.'] }); }
    if (importInput.current) importInput.current.value = '';
  }
  function applyImport(replace: boolean) {
    if (!itemImport || itemImport.errors.length || (!replace && appendErrors.length)) return;
    if (replace) setReplaced(structuredClone(p.loot.items));
    if (replace) for (const item of p.loot.items) { report(`weight-${item.id}`, false); report(`token-${item.id}`, false); }
    update(d => { d.loot.items = replace ? itemImport.items : [...d.loot.items, ...itemImport.items]; });
    setRemoved(undefined); setItemImport(undefined);
  }
  return <div className="config-layout"><div className="config-main">
    {page === 'overview' && <>
      <h2>Project overview</h2><p className="lead">Configure your project settings and generation target.</p>
      <div className="fields three"><Field label="Project name"><input value={p.name} maxLength={80} onChange={e => update(d => { d.name = e.target.value; })} /></Field>
        <Field label="Mechanic"><select value={p.mechanic} onChange={e => update(d => { d.mechanic = e.target.value as StudioProject['mechanic']; d.collection.standard = d.mechanic === 'reveal' ? 'erc721' : 'erc1155'; })}><option value="lootbox">Lootbox</option><option value="reveal">NFT reveal</option></select></Field>
        <Field label="Asset standard"><select value={p.collection.standard} onChange={e => update(d => { d.collection.standard = e.target.value as StudioProject['collection']['standard']; })}><option value="erc1155">ERC-1155</option><option value="erc721">ERC-721</option></select></Field></div>
      <section className="ruled"><Choices label="Generation target" value={p.integration} onChange={v => update(d => { d.integration = v; })} options={[{ value: 'new', label: 'New project', description: 'Start with a consumer scaffold, configuration and agent instructions.' }, { value: 'existing', label: 'Existing project', description: 'Export boilerplate for manual integration. Your repository is not edited automatically.' }]} /></section>
      <section className="ruled"><h3>Target network</h3><Field label="Deployment reference" hint="Confirm the manifest and live configuration before integration."><select value={p.network} onChange={e => update(d => { d.network = e.target.value as StudioProject['network']; })}><option value="arc-testnet">Arc Testnet · static reference</option><option value="arc-mainnet">Arc Mainnet · static reference</option></select></Field></section>
      <div className="actions"><button className="primary" onClick={() => navigate('mechanic')}>{p.mechanic === 'lootbox' ? 'Configure items' : 'Configure reveal'} →</button><button onClick={() => navigate('files')}>View files</button></div>
    </>}
    {page === 'mechanic' && <>
      <h2>{p.mechanic === 'lootbox' ? 'Items & weights' : 'Reveal settings'}</h2><p className="lead">{p.mechanic === 'lootbox' ? 'One independent weighted draw per opening.' : 'Assign metadata across a fixed participating token set.'}</p>
      <div className="fields"><Field label="Collection name"><input value={p.collection.name} maxLength={80} onChange={e => update(d => { d.collection.name = e.target.value; })} /></Field><Field label="Symbol"><input value={p.collection.symbol} maxLength={16} onChange={e => update(d => { d.collection.symbol = e.target.value; })} /></Field></div>
      {p.mechanic === 'lootbox' ? <>
        <div className="table-scroll"><table className="items-table metadata-items"><thead><tr><th><span className="sr-only">Preview</span></th><th>Item</th><th>Metadata URI</th><th>Token ID</th><th>Weight</th><th>Chance</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{p.loot.items.map((item, i) => {
          const tokenId = item.tokenId ?? String(i);
          const duplicate = p.loot.items.some((other, j) => j !== i && (other.tokenId ?? String(j)) === tokenId);
          return <tr key={item.id}><td><MetadataPreview uri={item.metadataUri} tokenId={tokenId} itemName={item.name} onUseName={name => update(d => { d.loot.items[i].name = name; })} /></td>
            <td><input aria-label={`Item ${i + 1} name`} value={item.name} maxLength={80} onChange={e => update(d => { d.loot.items[i].name = e.target.value; })} /></td>
            <td><input aria-label={`${item.name || `Item ${i + 1}`} metadata URI`} value={item.metadataUri} maxLength={MAX_URI_LENGTH} onChange={e => update(d => { d.loot.items[i].metadataUri = e.target.value; })} /></td>
            <td><TokenIdField label={`${item.name || `Item ${i + 1}`} token ID`} value={item.tokenId} fallback={String(i)} duplicate={duplicate} report={report} fieldKey={`token-${item.id}`} onChange={value => update(d => { if (value === undefined) delete d.loot.items[i].tokenId; else d.loot.items[i].tokenId = value; })} /></td>
            <td><NumberField label={`Weight for ${item.name || `item ${i + 1}`}`} value={item.weight} max={1_000_000} onChange={n => update(d => { d.loot.items[i].weight = n; })} {...numeric(`weight-${item.id}`)} /></td>
            <td className="mono">{total > 0 ? `${(item.weight / total * 100).toFixed(1)}%` : '—'}</td>
            <td><button className="icon-button" aria-label={`Remove ${item.name || `item ${i + 1}`}`} onClick={() => { setRemoved({ item, index: i }); report(`weight-${item.id}`, false); report(`token-${item.id}`, false); update(d => { d.loot.items.splice(i, 1); }); }}>×</button></td></tr>;
        })}</tbody></table></div>
        {p.loot.items.length === 0 && <p className="notice">Add an item to define your loot table.</p>}
        <p className="token-id-hint">Blank token IDs use the row index. ERC-1155 {'{id}'} is replaced with 64 lowercase hexadecimal characters. Chance is calculated from weights.</p>
        <div className="actions item-actions"><button disabled={p.loot.items.length >= MAX_ITEMS} onClick={() => update(d => { d.loot.items.push({ id: crypto.randomUUID(), name: '', metadataUri: '', weight: 1 }); })}>+ Add item</button><button onClick={() => importInput.current?.click()}>Import JSON / CSV</button>{removed && <button disabled={p.loot.items.length >= MAX_ITEMS} onClick={() => { update(d => { d.loot.items.splice(Math.min(removed.index, d.loot.items.length), 0, removed.item); }); setRemoved(undefined); }}>Undo removal</button>}{replaced && <button onClick={() => { for (const item of p.loot.items) { report(`weight-${item.id}`, false); report(`token-${item.id}`, false); } update(d => { d.loot.items = replaced; }); setReplaced(undefined); }}>Undo replacement</button>}</div>
        <input ref={importInput} type="file" accept=".json,.csv,application/json,text/csv" className="sr-only" aria-label="Import loot items" onChange={e => importItems(e.target.files?.[0])} />
        {itemImport && <section className="item-import" aria-label="Item import preview"><h3>Review item import</h3><p>{itemImport.items.length} parsed items. JSON accepts an array or an items array. CSV headers: name,metadataUri,weight,tokenId (optional).</p>{itemImport.errors.length > 0 && <ul className="import-errors">{itemImport.errors.map((error, i) => <li key={i}>{error}</li>)}</ul>}{itemImport.items.length > 0 && <div className="table-scroll"><table><thead><tr><th>Name</th><th>Weight</th><th>Token ID</th><th>Metadata URI</th></tr></thead><tbody>{itemImport.items.map((item, i) => <tr key={item.id}><td>{item.name}</td><td>{item.weight}</td><td>{item.tokenId ?? `Row index (${i})`}</td><td>{item.metadataUri || 'Not provided'}</td></tr>)}</tbody></table></div>}{appendErrors.length > 0 && <p className="muted">Append unavailable: {appendErrors.join(' ')}</p>}<div className="actions"><button disabled={itemImport.errors.length > 0 || appendErrors.length > 0} onClick={() => applyImport(false)}>Append items</button><button disabled={itemImport.errors.length > 0} onClick={() => applyImport(true)}>Replace table</button><button onClick={() => setItemImport(undefined)}>Cancel import</button></div><p className="muted">Replace keeps one undo snapshot. Existing metadata previews are not imported.</p></section>}
        <div className="fields ruled"><NumberField label="Maximum openings" value={p.loot.maxOpenings} min={1} onChange={n => update(d => { d.loot.maxOpenings = n; })} {...numeric('max-openings')} /><NumberField label="Maximum collection supply" value={p.collection.maxSupply} min={1} onChange={n => update(d => { d.collection.maxSupply = n; })} {...numeric('max-supply')} /></div>
      </> : <>
        <div className="fields"><NumberField label="Maximum supply / token count" value={p.collection.maxSupply} min={1} max={256} onChange={n => update(d => { d.collection.maxSupply = n; })} {...numeric('max-supply')} /><Field label="Metadata base URI"><input maxLength={MAX_URI_LENGTH} value={p.collection.metadataBaseUri} onChange={e => update(d => { d.collection.metadataBaseUri = e.target.value; })} placeholder="ipfs://collection/" /></Field></div>
        <section className="ruled"><h3>Participating tokens</h3><p className="mono">Token IDs 0–{Math.max(0, p.collection.maxSupply - 1)} · {p.collection.maxSupply} tokens</p><p className="muted">Shuffle a fixed token set. Freeze participating token IDs and metadata before requesting randomness. Supports up to 256 participating entries. New collections reveal after the configured supply is fully minted. Excluded premints keep their fixed prefix metadata.</p></section>
      </>}
      <section className="ruled"><h3>Optional modules</h3><p className="muted">{p.integration === 'new' ? 'Premint and royalties are included in the new collection template. Review configuration and contract behavior before deployment.' : 'Premint and royalty choices become requirements for your existing collection integration.'}</p><button onClick={() => navigate('modules')}>Configure modules →</button></section>
      <div className="actions"><button className="primary" onClick={() => navigate('files')}>View generated files →</button></div>
    </>}
    {page === 'payment' && <>
      <h2>Payment & recovery</h2><p className="lead">Configure application payments, RNG fee payer and recovery responsibility.</p>
      <p className="notice">Application sale pricing, fee sponsorship and custom refund routing are exported as integration requirements. The reference consumer charges only the RNG fee.</p><h3>Application payment</h3><Field label="Price per opening or mint (USDC)" hint="Application payments are accounted for separately from the RNG fee."><input inputMode="decimal" value={p.payment.price} onChange={e => update(d => { d.payment.price = e.target.value; })} /></Field>
      <Field label="Application payment on expiry"><select value={p.payment.applicationRefund} onChange={e => update(d => { d.payment.applicationRefund = e.target.value as StudioProject['payment']['applicationRefund']; })}><option value="refund-on-expiry">Refund when no proof is accepted</option><option value="developer-defined">Developer-defined recovery</option></select></Field>
      <section className="ruled"><h3>Randomness fee</h3><Choices label="RNG fee payer" value={p.payment.rngPayer} options={[{ value: 'user', label: 'User' }, { value: 'developer', label: 'Developer' }]} onChange={v => update(d => { d.payment.rngPayer = v; })} />
      <Field label="Fixed refund recipient policy" hint="Snapshot the recipient address when requesting randomness."><select value={p.payment.refundRecipient} onChange={e => update(d => { d.payment.refundRecipient = e.target.value as StudioProject['payment']['refundRecipient']; })}><option value="payer">Original payer</option><option value="developer">Developer</option><option value="custom">Custom recipient</option></select></Field>
      {p.payment.refundRecipient !== 'payer' && <Field label="Public refund recipient address"><input maxLength={MAX_ADDRESS_LENGTH} value={p.payment.refundAddress} placeholder="0x…" onChange={e => update(d => { d.payment.refundAddress = e.target.value; })} /></Field>}</section>
      <section className="ruled"><Choices label="Recovery handled by" value={p.payment.recovery} options={[{ value: 'user', label: 'User' }, { value: 'developer', label: 'Developer' }, { value: 'both', label: 'Both' }]} onChange={v => update(d => { d.payment.recovery = v; })} /><p className="muted">Defines who your application asks to submit recovery transactions.</p><p className="notice">Protocol refunds are permissionless and pay the fixed recipient.</p></section>
    </>}
    {page === 'modules' && <>
      <h2>Optional modules</h2><p className="lead">Record the collection features for your implementation brief.</p>
      <details className="module" open><summary>Premint</summary><label className="check"><input type="checkbox" checked={p.modules.premint.enabled} onChange={e => { if (!e.target.checked) report('premint', false); update(d => { d.modules.premint.enabled = e.target.checked; }); }} /> Include premint requirements</label>{p.modules.premint.enabled && <><div className="fields"><NumberField label="Premint quantity" value={p.modules.premint.quantity} max={p.collection.maxSupply} onChange={n => update(d => { d.modules.premint.quantity = n; })} {...numeric('premint')} /><Field label="Allocation recipient"><input placeholder="Public recipient address" maxLength={MAX_ADDRESS_LENGTH} value={p.modules.premint.recipient} onChange={e => update(d => { d.modules.premint.recipient = e.target.value; })} /></Field></div>{p.mechanic === 'reveal' && <label className="check"><input type="checkbox" checked={p.modules.premint.includeInReveal} onChange={e => update(d => { d.modules.premint.includeInReveal = e.target.checked; })} />Include premints in reveal</label>}<p className="muted">{p.modules.premint.quantity} of {p.collection.maxSupply} tokens reserved before public minting.</p>{p.integration === 'new' && p.mechanic === 'lootbox' && <p className="muted">Premint allocates the first configured item token ID. Maximum supply counts all NFT units, including premints and reserved openings.</p>}</>}</details>
      <details className="module" open><summary>Royalties</summary><label className="check"><input type="checkbox" checked={p.modules.royalty.enabled} onChange={e => { if (!e.target.checked) report('royalty', false); update(d => { d.modules.royalty.enabled = e.target.checked; }); }} /> Include royalty requirements</label>{p.modules.royalty.enabled && <div className="fields"><NumberField label="Royalty rate (basis points)" value={p.modules.royalty.bps} max={10000} onChange={n => update(d => { d.modules.royalty.bps = n; })} {...numeric('royalty')} /><Field label="Royalty receiver"><input placeholder="0x…" maxLength={MAX_ADDRESS_LENGTH} value={p.modules.royalty.recipient} onChange={e => update(d => { d.modules.royalty.recipient = e.target.value; })} /></Field></div>}<p className="muted">{p.modules.royalty.bps / 100}% · ERC-2981 signals royalties; marketplaces decide enforcement.</p></details>
      <p className="notice">{p.integration === 'new' ? 'The new collection template includes selected premint and royalty behavior. Sale payments, fee sponsorship and custom refund policies remain integration work.' : 'Module settings update the configuration and agent brief for your existing collection. Implement and test the required hooks in your application.'}</p><button className="primary" onClick={() => navigate('files')}>View generated files →</button>
    </>}
  </div><aside className="summary-rail">
    {page === 'payment' ? <><h3>Recovery rules</h3><p>60 seconds is the proof-acceptance deadline.</p><hr /><p>Expired without accepted proof: request the protocol refund.</p><hr /><p>Accepted proof, failed callback: retry the same word. No RNG fee refund.</p><hr /><p className="muted">Application delivery is defined by your integration.</p></> : page === 'modules' ? <><h3>Included in export</h3><p>Project configuration</p><p>AGENTS.md</p><p>Agent prompt</p><hr /><p className="muted">Generated files and instructions reflect the same choices.</p></> : p.mechanic === 'lootbox' ? <><h3>{page === 'mechanic' ? 'Probability' : 'Configuration'}</h3>{p.loot.items.map(item => <div className="probability" key={item.id}><div><span>{item.name || 'Unnamed item'}</span><span>{total > 0 ? `${(item.weight / total * 100).toFixed(1)}%` : '—'}</span></div><div className="bar"><span style={{ width: `${total > 0 ? item.weight / total * 100 : 0}%` }} /></div></div>)}<hr /><p>Total weight <span className="right">{total}</span></p><p className="muted">Independent draws do not guarantee stock or rarity counts.</p></> : <><h3>Reveal plan</h3><p>{p.collection.maxSupply} token IDs</p><p>{p.collection.maxSupply} metadata entries</p><p>{p.modules.premint.enabled ? p.modules.premint.quantity : 0} premints</p><p>One fixed assignment</p><hr /><p className="muted">Freeze inputs before requesting randomness.</p></>}
  </aside></div>;
}
